// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj4ejeNp4dez1wWPZkBs_WQZmNRYmdwMA',
    appId: '1:243711370792:web:add2f92e940200688e371d',
    messagingSenderId: '243711370792',
    projectId: 'fir-course-15c17',
    authDomain: 'fir-course-15c17.firebaseapp.com',
    storageBucket: 'fir-course-15c17.firebasestorage.app',
    measurementId: 'G-MWNSRKYCKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuh_lbWGiuArTL8y79gYwl22Y05BXxN5w',
    appId: '1:243711370792:android:8e2e63d48a22fb2d8e371d',
    messagingSenderId: '243711370792',
    projectId: 'fir-course-15c17',
    storageBucket: 'fir-course-15c17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVZKAIsOjXG9RExI238cErNOpFwA4X1C4',
    appId: '1:243711370792:ios:cd8c37fe92f7980a8e371d',
    messagingSenderId: '243711370792',
    projectId: 'fir-course-15c17',
    storageBucket: 'fir-course-15c17.firebasestorage.app',
    iosBundleId: 'com.example.dispensary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVZKAIsOjXG9RExI238cErNOpFwA4X1C4',
    appId: '1:243711370792:ios:cd8c37fe92f7980a8e371d',
    messagingSenderId: '243711370792',
    projectId: 'fir-course-15c17',
    storageBucket: 'fir-course-15c17.firebasestorage.app',
    iosBundleId: 'com.example.dispensary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj4ejeNp4dez1wWPZkBs_WQZmNRYmdwMA',
    appId: '1:243711370792:web:b48a131de576538b8e371d',
    messagingSenderId: '243711370792',
    projectId: 'fir-course-15c17',
    authDomain: 'fir-course-15c17.firebaseapp.com',
    storageBucket: 'fir-course-15c17.firebasestorage.app',
    measurementId: 'G-HV3KHDEKCJ',
  );
}
